// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi_BNrklbP-Ou-6z_xzE7_8ge6xxubXG4',
    appId: '1:401633629557:web:5c17b4f9c8b10306232f3c',
    messagingSenderId: '401633629557',
    projectId: 'taag-36265',
    authDomain: 'taag-36265.firebaseapp.com',
    storageBucket: 'taag-36265.appspot.com',
    measurementId: 'G-RV4JJMT3V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBlwUVnfTY4KNPiouP2uBrZGJjPi183J4',
    appId: '1:401633629557:android:ba9fb2d7c172d0f3232f3c',
    messagingSenderId: '401633629557',
    projectId: 'taag-36265',
    storageBucket: 'taag-36265.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3zCfEDLoF_4xlv9KDBby7bCloBZVVUhA',
    appId: '1:401633629557:ios:9f3b1dc395b69d01232f3c',
    messagingSenderId: '401633629557',
    projectId: 'taag-36265',
    storageBucket: 'taag-36265.appspot.com',
    androidClientId: '401633629557-o6ndka04jnetgi2t385c4pd7isa8srdc.apps.googleusercontent.com',
    iosClientId: '401633629557-jto3jag26cef9dqt64he5e4760ah3aau.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminTaag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3zCfEDLoF_4xlv9KDBby7bCloBZVVUhA',
    appId: '1:401633629557:ios:9f3b1dc395b69d01232f3c',
    messagingSenderId: '401633629557',
    projectId: 'taag-36265',
    storageBucket: 'taag-36265.appspot.com',
    androidClientId: '401633629557-o6ndka04jnetgi2t385c4pd7isa8srdc.apps.googleusercontent.com',
    iosClientId: '401633629557-jto3jag26cef9dqt64he5e4760ah3aau.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminTaag',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi_BNrklbP-Ou-6z_xzE7_8ge6xxubXG4',
    appId: '1:401633629557:web:f3272671b563021e232f3c',
    messagingSenderId: '401633629557',
    projectId: 'taag-36265',
    authDomain: 'taag-36265.firebaseapp.com',
    storageBucket: 'taag-36265.appspot.com',
    measurementId: 'G-P6LDKCVQW2',
  );
}
